title: PowerSheet
description: We develop tools, add-ons and templates for Google Sheets and other Google Workspace products
# theme: minima
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# remote_theme: THEME-NAME
include: .well-known
